### ISSUE TITLE
make read the docs 

### ISSUE THREAD

**Issue by alejoe91** [SpikeInterface/spikeextractors#149]
- recording extractor
- sorting extractor
- available extractors
- using a probe file
- (curating results)

**Comment by colehurwitz** [comment]
I will look into doing this soon

**Comment by alejoe91** [comment]
I've started :) will make a PR later, than we can work on that

**Comment by colehurwitz** [comment]
Oh, nice :). Sounds good!

**Comment by samuelgarcia** [comment]
@alejoe91 : I experienced difficulties in the past with read the doc and auto build because of dependencies. Maybe it is easier today. I would advice to try something simple at the begenning and see how it build. Then you can make more complexe. For instance with sphink-galery plugin (to avoid notebook in git).

**Comment by alejoe91** [comment]
@colehurwitz do you have time to fill in the missing parts? :)

**Comment by colehurwitz** [comment]
Yes, I can get to those in the near future!

**Comment by alejoe91** [comment]
Still missing the probe file handling

**Comment by alejoe91** [comment]
but there's another issue open
