### ISSUE TITLE
Add sampling frequency to SortingExtractors that support it

### ISSUE THREAD

**Issue by colehurwitz** [SpikeInterface/spikeextractors#169]
I was thinking an optional sampling_frequency argument can be added to sorting extractors that do not have access to the sampling rate:

MDASortingExtractor(firings, sampling_frequency=None)

**Comment by colehurwitz** [comment]
@samuelgarcia  Is the .npz sampling frequency code ok? If so, I can uncomment it and commit it

**Comment by samuelgarcia** [comment]
I think it is better to have explicitly self._sampling_frequency = None for theses format.

The only consequence is that the user will have to provide manually for SpikeComparison otherwise it will raire an error.


About npz you can uncomments but it has never been tested.
So please add 2 line in the test_nzp....

**Comment by colehurwitz** [comment]
I can add that as a test!

**Comment by colehurwitz** [comment]
Just realized a bit of a problem... numpy sorting extractors don't support sampling frequency and we use it in our tests to write to different formats.

**Comment by colehurwitz** [comment]
Should we add that to NumpySortingExtractor as an argument that is None by default?

**Comment by samuelgarcia** [comment]
Yes.
