### ISSUE TITLE
SortingExtractor object, change spike_train

### ISSUE THREAD

**Issue by llobetv** [SpikeInterface/spikeextractors#381]
Hi,
I try for several function (merge, remove redundant, alignement) to change spike_train value from sorting object but it appear that in each sorting object the original spike_train list is save with different name. 

What is the best way to have something stable? (switch to sort_cache everytimes?)

Cheer,
Victor

**Comment by alejoe91** [comment]
Hi Victor,

Unfortunately as you noticed there is no proper way of changing the spiketrains outside of the curation module of spiketoolkit, and this is the case because we abstract the retrieval of the data with the abstract methods (e.g. `get_unit_spike_train`).

If you have suggestions (like removing duplicates) for some standard modifications they should be implemented in the curation module. For your own use, you could retrieve all the spike trains, modify them, make a new `NumpySortingExtractor` with the modified spike trains, and cache it.

Cheers
Alessio

**Comment by llobetv** [comment]
OK, 
Then we'll probably try to implemented some common function in the curation module,

Thanks
